parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '5555'
    database_name: drinkwith
    database_user: drinkwith
    database_password: drinkwith
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 443ded0b91ef5af9fc4dea42f2b383050f0f1fcb
    database_path: null
