drink_with_main:
    resource: "@DrinkWithMainBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

drink_with_user:
    resource: "@DrinkWithUserBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /user

